"""baseline_relacional_new_records

Revision ID: 4c760dc0230c
Revises:
Create Date: 2026-08-31 18:15:06.815323

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4c760dc0230c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=90), nullable=False),
        sa.Column("prefijo_codigo", sa.String(length=5), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("imagen", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prefijo_codigo ~ '^[A-Z0-9]{3,5}$'", name="ck_categorias_prefijo_codigo"
        ),
        sa.CheckConstraint(
            "char_length(btrim(nombre)) BETWEEN 2 AND 80",
            name="ck_categorias_nombre_valido",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    with op.batch_alter_table("categorias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categorias_prefijo_codigo"), ["prefijo_codigo"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_categorias_slug"), ["slug"], unique=True)

    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "rol", sa.String(length=20), server_default="cliente", nullable=False
        ),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("direccion", sa.String(length=200), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "fecha_registro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email ~ '^[^[:space:]@]+@[^[:space:]@]+\\.[^[:space:]@]+$'",
            name="ck_usuarios_email_formato",
        ),
        sa.CheckConstraint(
            "rol IN ('cliente', 'administrador')", name="ck_usuarios_rol"
        ),
        sa.CheckConstraint(
            "char_length(btrim(nombre)) BETWEEN 2 AND 100",
            name="ck_usuarios_nombre_valido",
        ),
        sa.CheckConstraint(
            "email = lower(btrim(email))", name="ck_usuarios_email_normalizado"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuarios_email"), ["email"], unique=True)

    op.create_table(
        "discos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("album", sa.String(length=150), nullable=False),
        sa.Column("artista", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("precio_base", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("formato", sa.String(length=10), nullable=False),
        sa.Column("peso_kg", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column(
            "costo_envio_por_kg",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "costo_embalaje",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("imagen", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("formato IN ('CD', 'VINILO')", name="ck_discos_formato"),
        sa.CheckConstraint(
            "char_length(btrim(album)) BETWEEN 1 AND 150", name="ck_discos_album_valido"
        ),
        sa.CheckConstraint(
            "char_length(btrim(artista)) BETWEEN 1 AND 120",
            name="ck_discos_artista_valido",
        ),
        sa.CheckConstraint(
            "char_length(btrim(descripcion)) > 0", name="ck_discos_descripcion_valida"
        ),
        sa.CheckConstraint("costo_embalaje >= 0", name="ck_discos_costo_embalaje"),
        sa.CheckConstraint("costo_envio_por_kg >= 0", name="ck_discos_costo_envio"),
        sa.CheckConstraint("peso_kg > 0", name="ck_discos_peso"),
        sa.CheckConstraint("precio_base > 0", name="ck_discos_precio"),
        sa.CheckConstraint("stock >= 0", name="ck_discos_stock"),
        sa.ForeignKeyConstraint(
            ["categoria_id"], ["categorias.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discos_artista"), ["artista"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_discos_categoria_id"), ["categoria_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_discos_codigo"), ["codigo"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_discos_formato"), ["formato"], unique=False
        )

    op.create_table(
        "metodos_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.Column("marca", sa.String(length=30), nullable=False),
        sa.Column("ultimos4", sa.String(length=4), nullable=False),
        sa.Column("titular", sa.String(length=120), nullable=False),
        sa.Column("mes_vencimiento", sa.Integer(), nullable=False),
        sa.Column("anio_vencimiento", sa.Integer(), nullable=False),
        sa.Column(
            "predeterminado", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("fecha_verificacion", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "marca IN ('VISA', 'MASTERCARD', 'AMEX')", name="ck_metodos_pago_marca"
        ),
        sa.CheckConstraint("ultimos4 ~ '^[0-9]{4}$'", name="ck_metodos_pago_ultimos4"),
        sa.CheckConstraint(
            "anio_vencimiento BETWEEN 2020 AND 2100",
            name="ck_metodos_pago_anio_vencimiento",
        ),
        sa.CheckConstraint(
            "char_length(btrim(titular)) BETWEEN 3 AND 120",
            name="ck_metodos_pago_titular_valido",
        ),
        sa.CheckConstraint(
            "mes_vencimiento BETWEEN 1 AND 12", name="ck_metodos_pago_mes_vencimiento"
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    with op.batch_alter_table("metodos_pago", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metodos_pago_usuario_id"), ["usuario_id"], unique=False
        )

    op.create_table(
        "secuencias_codigo_categoria",
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("ultimo_numero", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "ultimo_numero >= 0", name="ck_secuencias_codigo_ultimo_numero"
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"], ["categorias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("categoria_id"),
    )
    op.create_table(
        "verificaciones_tarjeta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("token_verificacion", sa.String(length=64), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column("token_tarjeta", sa.String(length=120), nullable=False),
        sa.Column("marca", sa.String(length=30), nullable=False),
        sa.Column("ultimos4", sa.String(length=4), nullable=False),
        sa.Column("titular", sa.String(length=120), nullable=False),
        sa.Column("mes_vencimiento", sa.Integer(), nullable=False),
        sa.Column("anio_vencimiento", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_expiracion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("intentos", sa.Integer(), server_default="0", nullable=False),
        sa.Column("verificada", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "marca IN ('VISA', 'MASTERCARD', 'AMEX')", name="ck_verificaciones_marca"
        ),
        sa.CheckConstraint(
            "ultimos4 ~ '^[0-9]{4}$'", name="ck_verificaciones_ultimos4"
        ),
        sa.CheckConstraint(
            "anio_vencimiento BETWEEN 2020 AND 2100",
            name="ck_verificaciones_anio_vencimiento",
        ),
        sa.CheckConstraint(
            "char_length(btrim(titular)) BETWEEN 3 AND 120",
            name="ck_verificaciones_titular_valido",
        ),
        sa.CheckConstraint(
            "intentos BETWEEN 0 AND 3", name="ck_verificaciones_intentos"
        ),
        sa.CheckConstraint(
            "mes_vencimiento BETWEEN 1 AND 12", name="ck_verificaciones_mes_vencimiento"
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_verificacion"),
    )
    with op.batch_alter_table("verificaciones_tarjeta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verificaciones_tarjeta_usuario_id"),
            ["usuario_id"],
            unique=False,
        )

    op.create_table(
        "pedidos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=24), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("metodo_pago_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado", sa.String(length=20), server_default="PENDIENTE", nullable=False
        ),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_revision", sa.DateTime(timezone=True), nullable=True),
        sa.Column("administrador_revisor_id", sa.Integer(), nullable=True),
        sa.Column("motivo_rechazo", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "estado <> 'RECHAZADO' OR motivo_rechazo IS NOT NULL",
            name="ck_pedidos_rechazo_con_motivo",
        ),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')", name="ck_pedidos_estado"
        ),
        sa.CheckConstraint("total >= 0", name="ck_pedidos_total"),
        sa.ForeignKeyConstraint(
            ["administrador_revisor_id"], ["usuarios.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["metodo_pago_id"], ["metodos_pago.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pedidos_administrador_revisor_id"),
            ["administrador_revisor_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pedidos_cliente_id"), ["cliente_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pedidos_numero"), ["numero"], unique=True)

    op.create_table(
        "detalles_pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("disco_id", sa.Integer(), nullable=False),
        sa.Column("album", sa.String(length=150), nullable=False),
        sa.Column("artista", sa.String(length=120), nullable=False),
        sa.Column("formato", sa.String(length=10), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.CheckConstraint("cantidad > 0", name="ck_detalles_cantidad"),
        sa.CheckConstraint("precio_unitario >= 0", name="ck_detalles_precio_unitario"),
        sa.ForeignKeyConstraint(["disco_id"], ["discos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pedido_id"], ["pedidos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pedido_id", "disco_id", name="uq_detalles_pedido_disco"),
    )
    with op.batch_alter_table("detalles_pedido", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_detalles_pedido_disco_id"), ["disco_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_detalles_pedido_pedido_id"), ["pedido_id"], unique=False
        )

    op.create_table(
        "facturas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=30), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column(
            "fecha_emision",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ruta_pdf", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "tipo IN ('COMPROBANTE_PENDIENTE', 'FACTURA_FINAL')",
            name="ck_facturas_tipo",
        ),
        sa.ForeignKeyConstraint(["pedido_id"], ["pedidos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pedido_id", "tipo", name="uq_facturas_pedido_tipo"),
    )
    with op.batch_alter_table("facturas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_facturas_numero"), ["numero"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_facturas_pedido_id"), ["pedido_id"], unique=False
        )

    op.create_table(
        "transacciones_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("metodo_pago_id", sa.Integer(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "estado", sa.String(length=20), server_default="PENDIENTE", nullable=False
        ),
        sa.Column("referencia", sa.String(length=80), nullable=False),
        sa.Column("fecha_procesamiento", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')",
            name="ck_transacciones_estado",
        ),
        sa.CheckConstraint("monto >= 0", name="ck_transacciones_monto"),
        sa.ForeignKeyConstraint(
            ["metodo_pago_id"], ["metodos_pago.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["pedido_id"], ["pedidos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pedido_id"),
        sa.UniqueConstraint("referencia"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transacciones_pago")
    with op.batch_alter_table("facturas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_facturas_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_facturas_numero"))

    op.drop_table("facturas")
    with op.batch_alter_table("detalles_pedido", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detalles_pedido_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_detalles_pedido_disco_id"))

    op.drop_table("detalles_pedido")
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pedidos_numero"))
        batch_op.drop_index(batch_op.f("ix_pedidos_cliente_id"))
        batch_op.drop_index(batch_op.f("ix_pedidos_administrador_revisor_id"))

    op.drop_table("pedidos")
    with op.batch_alter_table("verificaciones_tarjeta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verificaciones_tarjeta_usuario_id"))

    op.drop_table("verificaciones_tarjeta")
    op.drop_table("secuencias_codigo_categoria")
    with op.batch_alter_table("metodos_pago", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metodos_pago_usuario_id"))

    op.drop_table("metodos_pago")
    with op.batch_alter_table("discos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discos_formato"))
        batch_op.drop_index(batch_op.f("ix_discos_codigo"))
        batch_op.drop_index(batch_op.f("ix_discos_categoria_id"))
        batch_op.drop_index(batch_op.f("ix_discos_artista"))

    op.drop_table("discos")
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_email"))

    op.drop_table("usuarios")
    with op.batch_alter_table("categorias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categorias_slug"))
        batch_op.drop_index(batch_op.f("ix_categorias_prefijo_codigo"))

    op.drop_table("categorias")
    # ### end Alembic commands ###
